---
- name: Backup Junos Configuration (manual way)
  hosts: juniper_switches
  connection: netconf
  gather_facts: no

  tasks:
    - name: Get running config (committed)
      junipernetworks.junos.junos_command:
        commands: "show configuration | display set"
      register: config_out

    - name: Save config to file
      copy:
        content: "{{ config_out.stdout[0] }}"
        dest: "/home/iass/junos_backup/{{ inventory_hostname }}_backup.txt"
