---
- name: Backup Junos configuration
  hosts: juniper_switches
  gather_facts: no
  connection: ansible.netcommon.netconf

  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    backup_file: "/tmp/{{ inventory_hostname }}_{{ timestamp }}.conf"

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Get Junos config
      junipernetworks.junos.junos_config:
        retrieve: "config"
      register: config_output

    - name: Save config to AWX pod (temporary)
      copy:
        content: "{{ config_output.config }}"
        dest: "{{ backup_file }}"
      delegate_to: localhost
