---
- name: Test Junos connectivity
  hosts: junos
  gather_facts: no
  collections:
    - junipernetworks.junos

  tasks:
    - name: Get Junos facts
      junipernetworks.junos.junos_facts:
      register: facts

    - name: Show Junos version
      debug:
        msg: "Hostname: {{ facts.ansible_facts.ansible_net_hostname }} - Version: {{ facts.ansible_facts.ansible_net_version }}"
