---
- name: Test Junos connectivity
  hosts: juniper_switches
  gather_facts: no
  connection: ansible.netcommon.netconf

  tasks:
    - name: Get Junos facts
      junipernetworks.junos.junos_facts:
      register: junos_facts

    - name: Show all facts (debugging)
      debug:
        var: junos_facts

    - name: Show important device info
      debug:
        msg: |
          Hostname : {{ junos_facts.ansible_facts.junos.hostname }}
          Version  : {{ junos_facts.ansible_facts.junos.version }}
          Model    : {{ junos_facts.ansible_facts.junos.model }}
          Serial   : {{ junos_facts.ansible_facts.junos.serialnumber }}
